FROM python:3.6.9

# Install pip3 and other packages
RUN apt-get update && apt-get install -y python3-pip \
&& pip3 install --upgrade pip \
&& pip3 install xlwt opencv-python numpy matplotlib pillow pathlib \
&& pip3 install pandas \