version: '3'
services:
  data-hiding:
    build:
      context: app
      dockerfile: Dockerfile
    volumes:
      - ./app/src:/app
    working_dir: /app
    command: ["python3", "test.py"]
  report-build:
    build:
      context: report
      dockerfile: Dockerfile
    volumes:
      - ./report/src:/app
    working_dir: /app
    command: ["pdflatex", "IT2033.tex"]
